### ISSUE TITLE
Cant import from src directly.

### ISSUE THREAD

**Issue by ghost** [department-stockholm/apollo-component#1]
When I try to import apollo-component from a react package like this,
`import { Query } from '@department/apollo-component/src'`

it gives me this error,
```
Module not found: Error: Can't resolve './state/renderState.js' in './node_modules/@department/apollo-component/src'
 @ ./node_modules/@department/apollo-component/src/index.js 52:19-52
```

I think this is because of your npmignore which ignores all files expect the whitelisted ones where the state folder is not whitelisted.

**Comment by slaskis** [comment]
Thanks for reporting, I can have a fix later today. May I ask why you're importing from src/ instead of directly?

**Comment by ghost** [comment]
Well actually I tried to import his project directly from `@department/component` in a webpack based project. And the default exported file is a .mjs file so I added that to webpack extensions and babel loader. But then my eslint started crying saying cannot detect .mjs file or something and wouldn't allow  compilation of my code.
I tried to load from source directly since it had an extension of .js but that failed because of this current issue (error).
So right now to subvert this I'm importing `@department/component/dist`. But yeah i guess 'src' or 'dist' is not the right way. I have to go to esland and find out.
Thanks anyways.
